config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("gouthelper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("blog/", include("gouthelper.blog.urls", namespace="blog")),
    path("contact/", include("gouthelper.contact.urls", namespace="contact")),
    path("", include("gouthelper.contents.urls", namespace="contents")),
    path("dateofbirths/", include("gouthelper.dateofbirths.urls", namespace="dateofbirths")),
    path("ethnicitys/", include("gouthelper.ethnicitys.urls", namespace="ethnicitys")),
    path("flareaids/", include("gouthelper.flareaids.urls", namespace="flareaids")),
    path("flares/", include("gouthelper.flares.urls", namespace="flares")),
    path("genders/", include("gouthelper.genders.urls", namespace="genders")),
    path("goalurates/", include("gouthelper.goalurates.urls", namespace="goalurates")),
    path("labs/", include("gouthelper.labs.urls", namespace="labs")),
    path("ppxaids/", include("gouthelper.ppxaids.urls", namespace="ppxaids")),
    path("ppxs/", include("gouthelper.ppxs.urls", namespace="ppxs")),
    path("treatments/", include("gouthelper.treatments.urls", namespace="treatments")),
    path("ultaids/", include("gouthelper.ultaids.urls", namespace="ultaids")),
    path("ults/", include("gouthelper.ults.urls", namespace="ults")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gouthelper/blog/urls.py
from django.urls import path  # type: ignore

from .views import BlogAuthorList, BlogDetail, BlogList, BlogTagList

app_name = "blog"

urlpatterns = [
    path("", BlogList.as_view(), name="blog"),
    path("<slug:slug>/", BlogDetail.as_view(), name="blog_detail"),
    path("by-author/<str:author>/", BlogAuthorList.as_view(), name="blog_author_list"),
    path("by-tag/<str:tag>/", BlogTagList.as_view(), name="blog_tag_list"),
]

gouthelper/contents/urls.py
from django.urls import path  # type: ignore

from .views import About, DecisionAids, Home, TreatmentAids

app_name = "contents"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("about/", About.as_view(), name="about"),
    path("decision-aids/", DecisionAids.as_view(), name="decision-aids"),
    path("treatment-aids/", TreatmentAids.as_view(), name="treatment-aids"),
]

gouthelper/labs/urls.py
from django.urls import path  # type: ignore

from .views import AboutHlab5801, AboutUrate, LabAbout

app_name = "labs"

urlpatterns = [
    path("about/", LabAbout.as_view(), name="about"),
    path("about/hlab5801/", AboutHlab5801.as_view(), name="about-hlab5801"),
    path("about/urate/", AboutUrate.as_view(), name="about-urate"),
]

gouthelper/ppxs/urls.py
from django.urls import path  # type: ignore

from .views import (
    PpxAbout,
    PpxCreate,
    PpxDetail,
    PpxPseudopatientCreate,
    PpxPseudopatientDetail,
    PpxPseudopatientUpdate,
    PpxUpdate,
)

app_name = "ppxs"

urlpatterns = [
    path("about/", PpxAbout.as_view(), name="about"),
    path("create/", PpxCreate.as_view(), name="create"),
    path("<uuid:pk>/", PpxDetail.as_view(), name="detail"),
    path("update/<uuid:pk>/", PpxUpdate.as_view(), name="update"),
    path("ppxaid/<uuid:ppxaid>/create", PpxCreate.as_view(), name="ppxaid-create"),
    path("goutpatient-create/<uuid:pseudopatient>/", PpxPseudopatientCreate.as_view(), name="pseudopatient-create"),
    path(
        "goutpatient-detail/<uuid:pseudopatient>/", view=PpxPseudopatientDetail.as_view(), name="pseudopatient-detail"
    ),
    path("goutpatient-update/<uuid:pseudopatient>/", PpxPseudopatientUpdate.as_view(), name="pseudopatient-update"),
]

gouthelper/treatments/urls.py
from django.urls import path  # type: ignore

from .views import AboutFlare, AboutPpx, AboutUlt, TreatmentAbout

app_name = "treatments"

urlpatterns = [
    path("about/", TreatmentAbout.as_view(), name="about"),
    path("about/flare/", AboutFlare.as_view(), name="about-flare"),
    path("about/ppx/", AboutPpx.as_view(), name="about-ppx"),
    path("about/ult/", AboutUlt.as_view(), name="about-ult"),
]

gouthelper/akis/models.py
from typing import TYPE_CHECKING, Literal, Union

from django.conf import settings  # type: ignore
from django.db import models  # type: ignore
from django.utils.functional import cached_property  # type: ignore
from django.utils.translation import gettext_lazy as _  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..dateofbirths.helpers import age_calc
from ..labs.helpers import labs_check_chronological_order_by_date_drawn
from ..rules import add_object, change_object, delete_object, view_object
from ..utils.helpers import get_qs_or_set
from ..utils.models import GoutHelperAidModel, GoutHelperModel
from .choices import Statuses
from .managers import AkiManager

if TYPE_CHECKING:
    from django.contrib.auth import get_user_model

    from ..genders.choices import Genders
    from ..labs.models import Creatinine
    from ..medhistorys.models import MedHistory

    User = get_user_model()


class Aki(
    RulesModelMixin,
    GoutHelperAidModel,
    GoutHelperModel,
    TimeStampedModel,
    metaclass=RulesModelBase,
):
    class Meta:
        rules_permissions = {
            "add": add_object,
            "change": change_object,
            "delete": delete_object,
            "view": view_object,
        }
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_status_is_valid",
                check=models.Q(status__in=Statuses.values),
            ),
        ]

    Statuses = Statuses
    user_foreign_key_fields: list[Literal["creatinine"]] = ["creatinine"]

    status = models.CharField(
        choices=Statuses.choices,
        default=Statuses.ONGOING,
        help_text=_("The status of this AKI."),
        max_length=20,
        verbose_name=_("Status"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    history = HistoricalRecords()

    objects = models.Manager()
    related_objects = AkiManager()

    @cached_property
    def age(self) -> int | None:
        return (
            age_calc(self.user.dateofbirth.value) if self.user else self.flare.age if hasattr(self, "flare") else None
        )

    @cached_property
    def ckd(self) -> Union["MedHistory", None]:
        return self.flare.ckd if hasattr(self, "flare") else None

    @cached_property
    def creatinines(self) -> list["Creatinine"] | models.QuerySet["Creatinine"]:
        list_or_qs = get_qs_or_set(self, "creatinine")
        if isinstance(list_or_qs, models.QuerySet):
            list_or_qs = list_or_qs.order_by("-date_drawn")
        else:
            labs_check_chronological_order_by_date_drawn(list_or_qs)
        return list_or_qs

    @cached_property
    def gender(self) -> Union["Genders", None]:
        return self.user.gender.value if self.user else self.flare.gender.value if hasattr(self, "flare") else None

    @cached_property
    def improving_with_creatinines(self) -> bool:
        return self.status == Statuses.IMPROVING and self.creatinines

    @cached_property
    def improving_with_creatinines_but_not_at_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            self.baselinecreatinine and not self.most_recent_creatinine.is_at_baseline and self.has_age_and_gender
        )

    @cached_property
    def improving_with_creatinines_stage_age_gender_no_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            not self.baselinecreatinine and self.stage and self.has_age_and_gender
        )

    @cached_property
    def improving_with_creatinines_age_gender_no_stage_or_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            not self.stage and not self.baselinecreatinine and self.has_age_and_gender
        )

    @cached_property
    def has_age_and_gender(self) -> bool:
        return self.age and self.gender is not None

    @cached_property
    def most_recent_creatinine(self) -> "Creatinine":
        return self.creatinines.first() if isinstance(self.creatinines, models.QuerySet) else self.creatinines[0]

    @cached_property
    def resolved(self) -> bool:
        return self.status == Statuses.RESOLVED

    def __str__(self) -> str:
        return f"AKI, {self.get_status_display()}"

    def update(self, status: Statuses) -> None:
        if self.status != status:
            self.status = status
            self.save()

gouthelper/blog/models.py
from autoslug import AutoSlugField  # type: ignore
from django.conf import settings  # type: ignore
from django.db import models  # type: ignore
from django.urls import reverse  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from markdownfield.models import RenderedMarkdownField  # type: ignore
from markdownfield.validators import VALIDATOR_CLASSY  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..utils.fields import GoutHelperMarkdownField
from ..utils.helpers import now_date
from ..utils.models import GoutHelperModel
from .choices import StatusChoices


class Blogtag(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store tags for posts."""

    history = HistoricalRecords()
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Blogpost(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store Blog Posts as HTML Markdown pages."""

    class Meta:
        constraints = [
            # Constrain title to be unique for entire table
            models.UniqueConstraint(
                fields=["title"],
                name="%(app_label)s_%(class)s_unique_title",
            ),
            # Enforce that status is a valid StatusChoices choice
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_valid_status",
                check=models.Q(status__in=StatusChoices.values),
            ),
        ]

    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blogposts")
    history = HistoricalRecords()
    published_date = models.DateField(default=now_date)
    slug = AutoSlugField(populate_from="title", unique=True)
    status = models.CharField(max_length=20, choices=StatusChoices.choices, default="draft")
    tags = models.ManyToManyField(to=Blogtag, related_name="posts", blank=True)
    text = GoutHelperMarkdownField(rendered_field="text_rendered", validator=VALIDATOR_CLASSY)
    text_rendered = RenderedMarkdownField()
    title = models.CharField(max_length=255)
    updated_date = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

gouthelper/contents/models.py
from django.db import models  # type: ignore
from django.utils.translation import gettext_lazy as _  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from markdownfield.models import RenderedMarkdownField  # type: ignore
from markdownfield.validators import VALIDATOR_CLASSY  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..utils.fields import GoutHelperMarkdownField
from ..utils.models import GoutHelperModel
from .choices import Contexts, Tags


class Content(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store HTML Markdown pages."""

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "context",
                    "slug",
                    "tag",
                ],
                name="%(app_label)s_%(class)s_unique_slug_tag_context",
            ),
            models.UniqueConstraint(
                fields=["slug"],
                condition=models.Q(context__isnull=True, tag__isnull=True),
                name="%(app_label)s_%(class)s_unique_slug_no_tag_context",
            ),
            # Enforce that you can only have one page with a slug and context but no tag
            models.UniqueConstraint(
                fields=["slug", "context"],
                condition=models.Q(tag__isnull=True),
                name="%(app_label)s_%(class)s_unique_slug_context_no_tag",
            ),
            # Enforce that context is a valid Contexts choice
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_valid_context",
                check=models.Q(context__in=Contexts.values),
            ),
            # Enforce that tag is a valid Tags choice
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_valid_tag",
                check=models.Q(tag__in=Tags.values),
            ),
        ]

    Contexts = Contexts
    Tags = Tags

    context = models.CharField(
        _("Context"), choices=Contexts.choices, max_length=255, null=True, blank=True, editable=False
    )
    history = HistoricalRecords()
    slug = models.SlugField(max_length=255)
    tag = models.CharField(max_length=255, choices=Tags.choices, null=True, blank=True)
    text = GoutHelperMarkdownField(rendered_field="text_rendered", validator=VALIDATOR_CLASSY)
    text_rendered = RenderedMarkdownField()

    def __str__(self):
        return f"Content: {self.slug} ({self.context}, {self.tag})"

gouthelper/dateofbirths/models.py
from datetime import timedelta
from typing import TYPE_CHECKING

from django.conf import settings
from django.db import models  # type: ignore
from django.urls import reverse_lazy
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _
from django_extensions.db.models import TimeStampedModel  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..utils.models import GoutHelperModel  # type: ignore

if TYPE_CHECKING:
    from datetime import date


# Create your models here.
class DateOfBirth(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model definition for DateOfBirth.
    Optional user OneToOneField for easy access to user's date of birth."""

    class Meta:
        # Create constraint such that date of birth is not any year before
        # exactly 18 years ago from now
        constraints = [
            models.CheckConstraint(
                check=models.Q(value__lte=(models.functions.Now() - timedelta(days=365 * 18))),
                name="dateofbirth_18_years_or_older",
            )
        ]

    value = models.DateField(
        _("Age"),
        help_text=format_lazy(
            """How old is the patient (range: 18-120)? <a href="{}" target="_next">Why do we need to know?</a>""",
            reverse_lazy("dateofbirths:about"),
        ),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        """Unicode representation of DateOfBirth."""
        return f"{self.value}"

    def value_needs_update(
        self,
        value: "date",
    ) -> bool:
        return self.value != value

    def update_value(
        self,
        value: "date",
        commit: bool = True,
    ) -> None:
        self.value = value
        if commit:
            self.full_clean()
            self.save()

gouthelper/templates/contents/about.html
{% extends "base.html" %}

{% block content %}
  <main class="container">
    {{ content.text_rendered | safe }}
  </main>
{% endblock content %}

gouthelper/templates/contents/decision-aids.html
{% extends "base.html" %}

{% block content %}
  <div class="container bodytainer">
    <div class="jumbotron">
      <h1>Decision Aids</h1>
      <p class="lead">Decision Aids are meant to answer common clinical questions about gout.</p>
      <hr class="my-4" />
      <p>
        GoutHelper takes information about a patient and his or her symptoms and applies
        empirical evidence, clinical guidelines, and rheumatology tribal knowledge to provide
        recommendations or advice. Like all things in medicine, there is a component of "art", also
        known as judgement or opinion, that is necessarily included in the Decision Aids. Some providers
        may disagree with subtle or even large parts of the recommendations.
      </p>
      <div class="row">
        <div class="col">
          <a class="btn btn-outline-primary samepage-link spacious-buttons w-100"
             href="#flare-card"
             role="button"><strong>Flare</strong></a>
        </div>
        <div class="col">
          <a class="btn btn-outline-primary samepage-link spacious-buttons w-100"
             href="#goalurate-card"
             role="button"><strong>GoalUrate</strong></a>
        </div>
        <div class="col">
          <a class="btn btn-outline-primary samepage-link spacious-buttons w-100"
             href="#ppx-card"
             role="button"><strong>Ppx</strong></a>
        </div>
        <div class="col">
          <a class="btn btn-outline-primary samepage-link spacious-buttons w-100"
             href="#ult-card"
             role="button"><strong>Ult</strong></a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm" id="decision-aids">{% include "flares/card.html" %}</div>
      <div class="col-sm" id="decision-aids">{% include "goalurates/card.html" %}</div>
    </div>
    <div class="row">
      <div class="col-sm">{% include "ppxs/card.html" %}</div>
      <div class="col-sm">{% include "ults/card.html" %}</div>
    </div>
    <a href="#top">Back to top</a>
  </div>
{% endblock content %}

gouthelper/templates/contents/home.html
{% extends "base.html" %}

{% load static %}
{% load project_tags %}

{% block content %}
  <main class="container">
    <div class="jumbotron">
      <h1>Welcome to GoutHelper</h1>
      <p class="lead">This is a site to help answer common clinical questions about gout.</p>
      <hr class="my-4" />
      <p>
        GoutHelper has clinical tools and information pages. Clinical tools take information about a
        patient and/or symptoms to provide useful information. Tools are either
        <strong><a class="samepage-link" href="{% url 'contents:treatment-aids' %}">Treatment Aids</a></strong>,
        which recommend a treatment for a specific scenario, or
        <strong><a class="samepage-link" href="{% url 'contents:decision-aids' %}">Decision Aids</a></strong>, which
        provide information about gout and/or whether a certain type of treatment is appropriate.
      </p>
      <p class="lead">
        <a class="btn btn-primary btn-lg"
           href="{% url 'contents:about' %}"
           role="button">About</a>
        <a class="btn btn-primary btn-lg"
           href="{% url 'blog:blog' %}"
           role="button">Blog</a>
      </p>
    </div>
    <div class="jumbotron bg-primary">
      <h1>Get Started</h1>
      <p class="lead">
        Start by creating a GoutPatient. If you'd like to save GoutPatients to reference later, create an account. If you know which tool you need, just pick that from the Navigation Bar.
      </p>
      <hr class="my-4" />
      <p>
        GoutPatients are a way to conslidate information and use multiple GoutHelper tools without duplicating information.
        They also don't require, and in fact don't allow, any Protected Health Information (PHI). <strong>GoutHelper assumes that all GoutPatients
        have gout. If you are uncertain about whether a patient's symptoms are due to gout, create a <a class="yellow-hyperlink" href="{% url 'flares:create' %}">Flare</a>
      to see what GoutHelper thinks.</strong>
    </p>
    <a class="btn btn-warning btn-lg"
       href="{% url 'users:pseudopatient-create' %}"
       role="button"><strong>Create GoutPatient</strong></a>
  </div>
</main>
{% endblock content %}

gouthelper/templates/contents/treatment-aids.html
{% extends "base.html" %}

{% block content %}
  <div class="container bodytainer">
    <div class="jumbotron">
      <h1>Treatment Aids</h1>
      <p class="lead">
        Treatment Aids determine what the ideal treatment is for each of the three types of gout treatment:
        urate-lowering therapy (<a href="{% url 'treatments:about-ult' %}">ULT</a>), <a href="{% url 'treatments:about-ppx' %}">prophylaxis</a>,
        and <a href="{% url 'treatments:about-flare' %}">flare</a> treatment.
      </p>
      <hr class="my-4" />
      <p>
        GoutHelper takes information about a patient and his or her symptoms and applies
        empirical evidence, clinical guidelines, and rheumatology tribal knowledge to provide
        treatment recommendations. Treatment Aids <strong>DO NOT</strong> tell you whether or not a certain
        type of treatment is appropriate for a patient. For that, you should use <a href="{% url 'contents:decision-aids' %}">Decision Aids</a>.
        Like all things in medicine, there is a component of "art", also
        known as judgement or opinion, that is necessarily included in the Decision Aids. Some providers
        may disagree with subtle or even large parts of the recommendations.
      </p>
      <div class="row">
        <div class="col">
          <a class="btn btn-outline-primary samepage-link spacious-buttons w-100"
             href="#flareaid-card"
             role="button"><strong>FlareAid</strong></a>
        </div>
        <div class="col">
          <a class="btn btn-outline-primary samepage-link spacious-buttons w-100"
             href="#ppxaid-card"
             role="button"><strong>PpxAid</strong></a>
        </div>
        <div class="col">
          <a class="btn btn-outline-primary samepage-link spacious-buttons w-100"
             href="#ultaid-card"
             role="button"><strong>UltAid</strong></a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm" id="decision-aids">{% include "flareaids/card.html" %}</div>
      <div class="col-sm">{% include "ppxaids/card.html" %}</div>
      <div class="col-sm">{% include "ultaids/card.html" %}</div>
    </div>
    <a href="#top">Back to top</a>
  </div>
{% endblock content %}