config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("gouthelper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("blog/", include("gouthelper.blog.urls", namespace="blog")),
    path("contact/", include("gouthelper.contact.urls", namespace="contact")),
    path("", include("gouthelper.contents.urls", namespace="contents")),
    path("dateofbirths/", include("gouthelper.dateofbirths.urls", namespace="dateofbirths")),
    path("ethnicitys/", include("gouthelper.ethnicitys.urls", namespace="ethnicitys")),
    path("flareaids/", include("gouthelper.flareaids.urls", namespace="flareaids")),
    path("flares/", include("gouthelper.flares.urls", namespace="flares")),
    path("genders/", include("gouthelper.genders.urls", namespace="genders")),
    path("goalurates/", include("gouthelper.goalurates.urls", namespace="goalurates")),
    path("labs/", include("gouthelper.labs.urls", namespace="labs")),
    path("ppxaids/", include("gouthelper.ppxaids.urls", namespace="ppxaids")),
    path("ppxs/", include("gouthelper.ppxs.urls", namespace="ppxs")),
    path("treatments/", include("gouthelper.treatments.urls", namespace="treatments")),
    path("ultaids/", include("gouthelper.ultaids.urls", namespace="ultaids")),
    path("ults/", include("gouthelper.ults.urls", namespace="ults")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gouthelper/blog/urls.py
from django.urls import path  # type: ignore

from .views import BlogAuthorList, BlogDetail, BlogList, BlogTagList

app_name = "blog"

urlpatterns = [
    path("", BlogList.as_view(), name="blog"),
    path("<slug:slug>/", BlogDetail.as_view(), name="blog_detail"),
    path("by-author/<str:author>/", BlogAuthorList.as_view(), name="blog_author_list"),
    path("by-tag/<str:tag>/", BlogTagList.as_view(), name="blog_tag_list"),
]

gouthelper/goalurates/urls.py
from django.urls import path  # type: ignore

from .views import (
    GoalUrateAbout,
    GoalUrateCreate,
    GoalUrateDetail,
    GoalUratePseudopatientCreate,
    GoalUratePseudopatientDetail,
    GoalUratePseudopatientUpdate,
    GoalUrateUpdate,
)

app_name = "goalurates"

urlpatterns = [
    path("about/", GoalUrateAbout.as_view(), name="about"),
    path("create/", GoalUrateCreate.as_view(), name="create"),
    path("<uuid:pk>/", GoalUrateDetail.as_view(), name="detail"),
    path("ppx/<uuid:ppx>/create", GoalUrateCreate.as_view(), name="ppx-create"),
    path("ultaid/<uuid:ultaid>/create", GoalUrateCreate.as_view(), name="ultaid-create"),
    path("update/<uuid:pk>/", GoalUrateUpdate.as_view(), name="update"),
    path(
        "goutpatient-create/<uuid:pseudopatient>/", GoalUratePseudopatientCreate.as_view(), name="pseudopatient-create"
    ),
    path(
        "goutpatient-detail/<uuid:pseudopatient>/",
        view=GoalUratePseudopatientDetail.as_view(),
        name="pseudopatient-detail",
    ),
    path(
        "goutpatient-update/<uuid:pseudopatient>/", GoalUratePseudopatientUpdate.as_view(), name="pseudopatient-update"
    ),
]

gouthelper/labs/urls.py
from django.urls import path  # type: ignore

from .views import AboutHlab5801, AboutUrate, LabAbout

app_name = "labs"

urlpatterns = [
    path("about/", LabAbout.as_view(), name="about"),
    path("about/hlab5801/", AboutHlab5801.as_view(), name="about-hlab5801"),
    path("about/urate/", AboutUrate.as_view(), name="about-urate"),
]

gouthelper/ppxs/urls.py
from django.urls import path  # type: ignore

from .views import (
    PpxAbout,
    PpxCreate,
    PpxDetail,
    PpxPseudopatientCreate,
    PpxPseudopatientDetail,
    PpxPseudopatientUpdate,
    PpxUpdate,
)

app_name = "ppxs"

urlpatterns = [
    path("about/", PpxAbout.as_view(), name="about"),
    path("create/", PpxCreate.as_view(), name="create"),
    path("<uuid:pk>/", PpxDetail.as_view(), name="detail"),
    path("update/<uuid:pk>/", PpxUpdate.as_view(), name="update"),
    path("ppxaid/<uuid:ppxaid>/create", PpxCreate.as_view(), name="ppxaid-create"),
    path("goutpatient-create/<uuid:pseudopatient>/", PpxPseudopatientCreate.as_view(), name="pseudopatient-create"),
    path(
        "goutpatient-detail/<uuid:pseudopatient>/", view=PpxPseudopatientDetail.as_view(), name="pseudopatient-detail"
    ),
    path("goutpatient-update/<uuid:pseudopatient>/", PpxPseudopatientUpdate.as_view(), name="pseudopatient-update"),
]

gouthelper/treatments/urls.py
from django.urls import path  # type: ignore

from .views import AboutFlare, AboutPpx, AboutUlt, TreatmentAbout

app_name = "treatments"

urlpatterns = [
    path("about/", TreatmentAbout.as_view(), name="about"),
    path("about/flare/", AboutFlare.as_view(), name="about-flare"),
    path("about/ppx/", AboutPpx.as_view(), name="about-ppx"),
    path("about/ult/", AboutUlt.as_view(), name="about-ult"),
]

gouthelper/akis/models.py
from typing import TYPE_CHECKING, Literal, Union

from django.conf import settings  # type: ignore
from django.db import models  # type: ignore
from django.utils.functional import cached_property  # type: ignore
from django.utils.translation import gettext_lazy as _  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..dateofbirths.helpers import age_calc
from ..labs.helpers import labs_check_chronological_order_by_date_drawn
from ..rules import add_object, change_object, delete_object, view_object
from ..utils.helpers import get_qs_or_set
from ..utils.models import GoutHelperAidModel, GoutHelperModel
from .choices import Statuses
from .managers import AkiManager

if TYPE_CHECKING:
    from django.contrib.auth import get_user_model

    from ..genders.choices import Genders
    from ..labs.models import Creatinine
    from ..medhistorys.models import MedHistory

    User = get_user_model()


class Aki(
    RulesModelMixin,
    GoutHelperAidModel,
    GoutHelperModel,
    TimeStampedModel,
    metaclass=RulesModelBase,
):
    class Meta:
        rules_permissions = {
            "add": add_object,
            "change": change_object,
            "delete": delete_object,
            "view": view_object,
        }
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_status_is_valid",
                check=models.Q(status__in=Statuses.values),
            ),
        ]

    Statuses = Statuses
    user_foreign_key_fields: list[Literal["creatinine"]] = ["creatinine"]

    status = models.CharField(
        choices=Statuses.choices,
        default=Statuses.ONGOING,
        help_text=_("The status of this AKI."),
        max_length=20,
        verbose_name=_("Status"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    history = HistoricalRecords()

    objects = models.Manager()
    related_objects = AkiManager()

    @cached_property
    def age(self) -> int | None:
        return (
            age_calc(self.user.dateofbirth.value) if self.user else self.flare.age if hasattr(self, "flare") else None
        )

    @cached_property
    def ckd(self) -> Union["MedHistory", None]:
        return self.flare.ckd if hasattr(self, "flare") else None

    @cached_property
    def creatinines(self) -> list["Creatinine"] | models.QuerySet["Creatinine"]:
        list_or_qs = get_qs_or_set(self, "creatinine")
        if isinstance(list_or_qs, models.QuerySet):
            list_or_qs = list_or_qs.order_by("-date_drawn")
        else:
            labs_check_chronological_order_by_date_drawn(list_or_qs)
        return list_or_qs

    @cached_property
    def gender(self) -> Union["Genders", None]:
        return self.user.gender.value if self.user else self.flare.gender.value if hasattr(self, "flare") else None

    @cached_property
    def improving_with_creatinines(self) -> bool:
        return self.status == Statuses.IMPROVING and self.creatinines

    @cached_property
    def improving_with_creatinines_but_not_at_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            self.baselinecreatinine and not self.most_recent_creatinine.is_at_baseline and self.has_age_and_gender
        )

    @cached_property
    def improving_with_creatinines_stage_age_gender_no_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            not self.baselinecreatinine and self.stage and self.has_age_and_gender
        )

    @cached_property
    def improving_with_creatinines_age_gender_no_stage_or_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            not self.stage and not self.baselinecreatinine and self.has_age_and_gender
        )

    @cached_property
    def has_age_and_gender(self) -> bool:
        return self.age and self.gender is not None

    @cached_property
    def most_recent_creatinine(self) -> "Creatinine":
        return self.creatinines.first() if isinstance(self.creatinines, models.QuerySet) else self.creatinines[0]

    @cached_property
    def resolved(self) -> bool:
        return self.status == Statuses.RESOLVED

    def __str__(self) -> str:
        return f"AKI, {self.get_status_display()}"

    def update(self, status: Statuses) -> None:
        if self.status != status:
            self.status = status
            self.save()

gouthelper/blog/models.py
from autoslug import AutoSlugField  # type: ignore
from django.conf import settings  # type: ignore
from django.db import models  # type: ignore
from django.urls import reverse  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from markdownfield.models import RenderedMarkdownField  # type: ignore
from markdownfield.validators import VALIDATOR_CLASSY  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..utils.fields import GoutHelperMarkdownField
from ..utils.helpers import now_date
from ..utils.models import GoutHelperModel
from .choices import StatusChoices


class Blogtag(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store tags for posts."""

    history = HistoricalRecords()
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Blogpost(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store Blog Posts as HTML Markdown pages."""

    class Meta:
        constraints = [
            # Constrain title to be unique for entire table
            models.UniqueConstraint(
                fields=["title"],
                name="%(app_label)s_%(class)s_unique_title",
            ),
            # Enforce that status is a valid StatusChoices choice
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_valid_status",
                check=models.Q(status__in=StatusChoices.values),
            ),
        ]

    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blogposts")
    history = HistoricalRecords()
    published_date = models.DateField(default=now_date)
    slug = AutoSlugField(populate_from="title", unique=True)
    status = models.CharField(max_length=20, choices=StatusChoices.choices, default="draft")
    tags = models.ManyToManyField(to=Blogtag, related_name="posts", blank=True)
    text = GoutHelperMarkdownField(rendered_field="text_rendered", validator=VALIDATOR_CLASSY)
    text_rendered = RenderedMarkdownField()
    title = models.CharField(max_length=255)
    updated_date = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

gouthelper/contents/models.py
from django.db import models  # type: ignore
from django.utils.translation import gettext_lazy as _  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from markdownfield.models import RenderedMarkdownField  # type: ignore
from markdownfield.validators import VALIDATOR_CLASSY  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..utils.fields import GoutHelperMarkdownField
from ..utils.models import GoutHelperModel
from .choices import Contexts, Tags


class Content(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store HTML Markdown pages."""

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "context",
                    "slug",
                    "tag",
                ],
                name="%(app_label)s_%(class)s_unique_slug_tag_context",
            ),
            models.UniqueConstraint(
                fields=["slug"],
                condition=models.Q(context__isnull=True, tag__isnull=True),
                name="%(app_label)s_%(class)s_unique_slug_no_tag_context",
            ),
            # Enforce that you can only have one page with a slug and context but no tag
            models.UniqueConstraint(
                fields=["slug", "context"],
                condition=models.Q(tag__isnull=True),
                name="%(app_label)s_%(class)s_unique_slug_context_no_tag",
            ),
            # Enforce that context is a valid Contexts choice
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_valid_context",
                check=models.Q(context__in=Contexts.values),
            ),
            # Enforce that tag is a valid Tags choice
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_valid_tag",
                check=models.Q(tag__in=Tags.values),
            ),
        ]

    Contexts = Contexts
    Tags = Tags

    context = models.CharField(
        _("Context"), choices=Contexts.choices, max_length=255, null=True, blank=True, editable=False
    )
    history = HistoricalRecords()
    slug = models.SlugField(max_length=255)
    tag = models.CharField(max_length=255, choices=Tags.choices, null=True, blank=True)
    text = GoutHelperMarkdownField(rendered_field="text_rendered", validator=VALIDATOR_CLASSY)
    text_rendered = RenderedMarkdownField()

    def __str__(self):
        return f"Content: {self.slug} ({self.context}, {self.tag})"

gouthelper/templates/goalurates/card.html
<div id="goalurate-card" class="card text-center spacious-cards">
  <div class="card-body">
    <h2 class="card-title">GoalUrate</h2>
    <p class="card-text">
      What is the goal uric acid for a patient on urate-lowering therapy (<a href="{% url 'treatments:about-ult' %}">ULT</a>)?
      The <strong>GoalUrate</strong> Decision Aid will help you figure out what uric acid to target as you titrate
      a patient's ULT. Not sure what is meant by the goal uric acid? No problem, check out our <strong>About</strong> page for it for a
      full explanation.
    </p>
    <a href="{% url 'goalurates:create' %}"
       class="btn btn-primary spacious-buttons">Create</a>
    <a href="{% url 'goalurates:about' %}"
       class="btn btn-primary spacious-buttons">About</a>
  </div>
</div>

gouthelper/templates/goalurates/goalurate_detail.html
{% extends "base.html" %}

{% load static %}
{% load project_tags %}

{% block heading %}
  <div class="row">
    <div class="col">
      <h1>GoalUrate</h1>
    </div>
    <div class="col align-items-center d-flex justify-content-end">
      <a type="button"
         class="btn btn-primary btn-lg spacious-buttons"
         href="{% url 'goalurates:about' %}"
         role="button">About</a>
      <a type="button"
         class="btn btn-primary btn-lg spacious-buttons"
         href="{% url 'goalurates:update' pk=object.pk %}"
         role="button">Update</a>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <span>Jump to:</span> <a class="samepage-link" href="#goal-uric-acid">Goal Uric Acid</a>
      | <a class="samepage-link" href="#explanations">Explanations</a>
    </div>
    <div class="col align-items-center d-flex justify-content-end">
      {% if object.user %}
        <span>{% include 'users/pseudopatient_link.html' with user=object.user %}</span>
      {% endif %}
    </div>
  </div>
{% endblock heading %}
{% block content %}
  <main role="main">
    <div class="container bodytainer">
      <hr size="3" color="dark" />
      <div id="goal-uric-acid">
        <div class="row">
          <div class="col">
            <h3>
              <u>Goal Uric Acid</u>: {{ object.get_goal_urate_display }}
            </h3>
            <p>{{ object.get_interpretation }}</p>
          </div>
        </div>
      </div>
      <div id="explanations">
        <hr size="3" color="dark" />
        <div class="row">
          <div class="col">
            <h3>
              <u>Explanations</u>
            </h3>
          </div>
        </div>
        <div class="accordion" id="accordionExplanations">
          {% for explanation in object.explanations %}
            {% include "explanation_accordion_item.html" with parent="accordionExplanations" id=explanation.0 label=explanation.1 bool=explanation.2 interp=explanation.3 %}
          {% endfor %}
        </div>
      </div>
      <a href="#top">Back to top</a>
    </div>
  </main>
{% endblock content %}

gouthelper/templates/goalurates/goalurate_detail_card.html
{% load project_tags %}

<div id="goalurate-card" class="card spacious-cards">
  <div class="card-body">
    {% if goalurate %}
      <div class="row">
        <div class="col">
          <h4>
            {% if goalurate.user %}
              <!-- djlint:off --><a href="{% url 'goalurates:pseudopatient-detail' goalurate.user.pk %}"><!-- djlint:on -->
            {% else %}
              <a href="{% url 'goalurates:detail' goalurate.pk %}">
              {% endif %}
            {{ goalurate }}</a>
          </h4>
        </div>
        <div class="col-auto align-items-center d-flex justify-content-end">
          <button class="btn btn-secondary"
                  id="goalurate_card_collapse_control"
                  data-bs-toggle="collapse"
                  data-bs-target="#goalurate_card_collapse"
                  type="button"
                  aria-expanded="true"
                  aria-controls="goalurate_card_collapse">Show</button>
        </div>
      </div>
      <div class="collapse mini-card-content" id="goalurate_card_collapse">
        <div class="row">
          <div class="col-md-12">
            {% call_method goalurate 'get_interpretation' False as interpretation %}
            <p class="card-text">{{ interpretation }}</p>
          </div>
        </div>
        {% if goalurate.user %}
          <a class="btn btn-primary"
             href="{% url 'goalurates:pseudopatient-update' goalurate.user.pk %}?next={{ object.get_absolute_url }}">Update</a>
        {% else %}
          <a class="btn btn-primary"
             href="{% url 'goalurates:update' goalurate.pk %}?next={{ object.get_absolute_url }}">Update</a>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'goalurates:about' %}">About</a>
      </div>
    {% else %}
      <div class="row">
        <div class="col">
          <h4 class="card-title">
            <a href="{% url 'goalurates:about' %}">Goal Urate</a>: none
          </h4>
        </div>
        {% if object|is_pseudopatient %}
          <div class="col-auto align-items-center d-flex justify-content-end">
            <a class="btn btn-primary"
               href="{% url 'goalurates:pseudopatient-create' object.pk %}?next={{ request.path }}">Create</a>
          </div>
        {% else %}
          <div class="col-auto align-items-center d-flex justify-content-end">
            <a class="btn btn-primary"
               href="{% url 'goalurates:create' %}?next={{ request.path }}">Create</a>
          </div>
        {% endif %}
      </div>
    {% endif %}
  </div>
</div>

gouthelper/templates/goalurates/goalurate_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load project_tags %}

{% block title %}
  {% if form.instance.created %}
    Edit GoalUrate
  {% else %}
    New GoalUrate
  {% endif %}
{% endblock title %}
{% block heading %}
  <h1>GoalUrate</h1>
{% endblock heading %}
{% block subheading %}
  Determine what {{ str_attrs.subject_the_pos }} goal uric acid level is.
{% endblock subheading %}
{% block content %}
  <main class="container">
    {% if form.instance.created %}
      {% if view.kwargs.pseudopatient %}
        <form class="form-horizontal"
              method="post"
              action="{% url 'goalurates:pseudopatient-update' object.user.pk %}">
          {% csrf_token %}
          {% crispy form %}
          {% include "_submit_button.html" %}
          {% include '_next_inputs.html' %}
        </form>
      {% else %}
        <form class="form-horizontal"
              method="post"
              action="{% url 'goalurates:update' object.pk %}">
          {% csrf_token %}
          {% crispy form %}
          {% include "_submit_button.html" %}
          {% include '_next_inputs.html' %}
        </form>
      {% endif %}
    {% else %}
      {% if view.kwargs.pseudopatient %}
        <form class="form-horizontal"
              method="post"
              action="{% url 'goalurates:pseudopatient-create' view.kwargs.pseudopatient %}">
          {% csrf_token %}
          {% crispy form %}
          {% include "_submit_button.html" %}
          {% include '_next_inputs.html' %}
        </form>
      {% else %}
        {% if ultaid %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'goalurates:ultaid-create' ultaid=ultaid %}">
            {% csrf_token %}
            {% crispy form %}
            {% include "_submit_button.html" %}
            {% include '_next_inputs.html' %}
          </form>
        {% else %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'goalurates:create' %}">
            {% csrf_token %}
            {% crispy form %}
            {% include "_submit_button.html" %}
            {% include '_next_inputs.html' %}
          </form>
        {% endif %}
      {% endif %}
    {% endif %}
  </main>
{% endblock content %}