config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("gouthelper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("blog/", include("gouthelper.blog.urls", namespace="blog")),
    path("contact/", include("gouthelper.contact.urls", namespace="contact")),
    path("", include("gouthelper.contents.urls", namespace="contents")),
    path("dateofbirths/", include("gouthelper.dateofbirths.urls", namespace="dateofbirths")),
    path("ethnicitys/", include("gouthelper.ethnicitys.urls", namespace="ethnicitys")),
    path("flareaids/", include("gouthelper.flareaids.urls", namespace="flareaids")),
    path("flares/", include("gouthelper.flares.urls", namespace="flares")),
    path("genders/", include("gouthelper.genders.urls", namespace="genders")),
    path("goalurates/", include("gouthelper.goalurates.urls", namespace="goalurates")),
    path("labs/", include("gouthelper.labs.urls", namespace="labs")),
    path("ppxaids/", include("gouthelper.ppxaids.urls", namespace="ppxaids")),
    path("ppxs/", include("gouthelper.ppxs.urls", namespace="ppxs")),
    path("treatments/", include("gouthelper.treatments.urls", namespace="treatments")),
    path("ultaids/", include("gouthelper.ultaids.urls", namespace="ultaids")),
    path("ults/", include("gouthelper.ults.urls", namespace="ults")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gouthelper/blog/urls.py
from django.urls import path  # type: ignore

from .views import BlogAuthorList, BlogDetail, BlogList, BlogTagList

app_name = "blog"

urlpatterns = [
    path("", BlogList.as_view(), name="blog"),
    path("<slug:slug>/", BlogDetail.as_view(), name="blog_detail"),
    path("by-author/<str:author>/", BlogAuthorList.as_view(), name="blog_author_list"),
    path("by-tag/<str:tag>/", BlogTagList.as_view(), name="blog_tag_list"),
]

gouthelper/flareaids/urls.py
from django.urls import path  # type: ignore

from .views import (
    FlareAidAbout,
    FlareAidCreate,
    FlareAidDetail,
    FlareAidPseudopatientCreate,
    FlareAidPseudopatientDetail,
    FlareAidPseudopatientUpdate,
    FlareAidUpdate,
)

app_name = "flareaids"

urlpatterns = [
    path("about/", FlareAidAbout.as_view(), name="about"),
    path("create/", FlareAidCreate.as_view(), name="create"),
    path("<uuid:pk>/", FlareAidDetail.as_view(), name="detail"),
    path("update/<uuid:pk>/", FlareAidUpdate.as_view(), name="update"),
    path("flare/<uuid:flare>/create", FlareAidCreate.as_view(), name="flare-create"),
    path(
        "goutpatient-create/<uuid:pseudopatient>/", FlareAidPseudopatientCreate.as_view(), name="pseudopatient-create"
    ),
    path(
        "goutpatient-create/<uuid:pseudopatient>/<uuid:flare>/",
        FlareAidPseudopatientCreate.as_view(),
        name="pseudopatient-flare-create",
    ),
    path(
        "goutpatient-detail/<uuid:pseudopatient>/",
        view=FlareAidPseudopatientDetail.as_view(),
        name="pseudopatient-detail",
    ),
    path(
        "goutpatient-detail/<uuid:pseudopatient>/<uuid:flare>/",
        view=FlareAidPseudopatientDetail.as_view(),
        name="pseudopatient-flare-detail",
    ),
    path(
        "goutpatient-update/<uuid:pseudopatient>/", FlareAidPseudopatientUpdate.as_view(), name="pseudopatient-update"
    ),
    path(
        "goutpatient-update/<uuid:pseudopatient>/<uuid:flare>/",
        view=FlareAidPseudopatientUpdate.as_view(),
        name="pseudopatient-flare-update",
    ),
]

gouthelper/labs/urls.py
from django.urls import path  # type: ignore

from .views import AboutHlab5801, AboutUrate, LabAbout

app_name = "labs"

urlpatterns = [
    path("about/", LabAbout.as_view(), name="about"),
    path("about/hlab5801/", AboutHlab5801.as_view(), name="about-hlab5801"),
    path("about/urate/", AboutUrate.as_view(), name="about-urate"),
]

gouthelper/ppxs/urls.py
from django.urls import path  # type: ignore

from .views import (
    PpxAbout,
    PpxCreate,
    PpxDetail,
    PpxPseudopatientCreate,
    PpxPseudopatientDetail,
    PpxPseudopatientUpdate,
    PpxUpdate,
)

app_name = "ppxs"

urlpatterns = [
    path("about/", PpxAbout.as_view(), name="about"),
    path("create/", PpxCreate.as_view(), name="create"),
    path("<uuid:pk>/", PpxDetail.as_view(), name="detail"),
    path("update/<uuid:pk>/", PpxUpdate.as_view(), name="update"),
    path("ppxaid/<uuid:ppxaid>/create", PpxCreate.as_view(), name="ppxaid-create"),
    path("goutpatient-create/<uuid:pseudopatient>/", PpxPseudopatientCreate.as_view(), name="pseudopatient-create"),
    path(
        "goutpatient-detail/<uuid:pseudopatient>/", view=PpxPseudopatientDetail.as_view(), name="pseudopatient-detail"
    ),
    path("goutpatient-update/<uuid:pseudopatient>/", PpxPseudopatientUpdate.as_view(), name="pseudopatient-update"),
]

gouthelper/users/urls.py
from django.urls import path

from .views import (
    pseudopatient_create_view,
    pseudopatient_delete_view,
    pseudopatient_detail_view,
    pseudopatient_flare_create_view,
    pseudopatient_list_view,
    pseudopatient_update_view,
    user_delete_view,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("pseudopatients/create/", view=pseudopatient_create_view, name="pseudopatient-create"),
    path(
        "pseudopatients/create/<uuid:flare>/", view=pseudopatient_flare_create_view, name="pseudopatient-flare-create"
    ),
    path("pseudopatients/delete/<uuid:pseudopatient>/", view=pseudopatient_delete_view, name="pseudopatient-delete"),
    path(
        "pseudopatients/provider-create/<str:username>/",
        view=pseudopatient_create_view,
        name="provider-pseudopatient-create",
    ),
    path(
        "pseudopatients/provider-create/<str:username>/<uuid:flare>/",
        view=pseudopatient_flare_create_view,
        name="provider-pseudopatient-flare-create",
    ),
    path("pseudopatients/<uuid:pseudopatient>/", view=pseudopatient_detail_view, name="pseudopatient-detail"),
    path("pseudopatients/<uuid:pseudopatient>/update/", view=pseudopatient_update_view, name="pseudopatient-update"),
    path("<str:username>/pseudopatients/", view=pseudopatient_list_view, name="pseudopatients"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~delete/", view=user_delete_view, name="delete"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

gouthelper/akis/models.py
from typing import TYPE_CHECKING, Literal, Union

from django.conf import settings  # type: ignore
from django.db import models  # type: ignore
from django.utils.functional import cached_property  # type: ignore
from django.utils.translation import gettext_lazy as _  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..dateofbirths.helpers import age_calc
from ..labs.helpers import labs_check_chronological_order_by_date_drawn
from ..rules import add_object, change_object, delete_object, view_object
from ..utils.helpers import get_qs_or_set
from ..utils.models import GoutHelperAidModel, GoutHelperModel
from .choices import Statuses
from .managers import AkiManager

if TYPE_CHECKING:
    from django.contrib.auth import get_user_model

    from ..genders.choices import Genders
    from ..labs.models import Creatinine
    from ..medhistorys.models import MedHistory

    User = get_user_model()


class Aki(
    RulesModelMixin,
    GoutHelperAidModel,
    GoutHelperModel,
    TimeStampedModel,
    metaclass=RulesModelBase,
):
    class Meta:
        rules_permissions = {
            "add": add_object,
            "change": change_object,
            "delete": delete_object,
            "view": view_object,
        }
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_status_is_valid",
                check=models.Q(status__in=Statuses.values),
            ),
        ]

    Statuses = Statuses
    user_foreign_key_fields: list[Literal["creatinine"]] = ["creatinine"]

    status = models.CharField(
        choices=Statuses.choices,
        default=Statuses.ONGOING,
        help_text=_("The status of this AKI."),
        max_length=20,
        verbose_name=_("Status"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    history = HistoricalRecords()

    objects = models.Manager()
    related_objects = AkiManager()

    @cached_property
    def age(self) -> int | None:
        return (
            age_calc(self.user.dateofbirth.value) if self.user else self.flare.age if hasattr(self, "flare") else None
        )

    @cached_property
    def ckd(self) -> Union["MedHistory", None]:
        return self.flare.ckd if hasattr(self, "flare") else None

    @cached_property
    def creatinines(self) -> list["Creatinine"] | models.QuerySet["Creatinine"]:
        list_or_qs = get_qs_or_set(self, "creatinine")
        if isinstance(list_or_qs, models.QuerySet):
            list_or_qs = list_or_qs.order_by("-date_drawn")
        else:
            labs_check_chronological_order_by_date_drawn(list_or_qs)
        return list_or_qs

    @cached_property
    def gender(self) -> Union["Genders", None]:
        return self.user.gender.value if self.user else self.flare.gender.value if hasattr(self, "flare") else None

    @cached_property
    def improving_with_creatinines(self) -> bool:
        return self.status == Statuses.IMPROVING and self.creatinines

    @cached_property
    def improving_with_creatinines_but_not_at_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            self.baselinecreatinine and not self.most_recent_creatinine.is_at_baseline and self.has_age_and_gender
        )

    @cached_property
    def improving_with_creatinines_stage_age_gender_no_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            not self.baselinecreatinine and self.stage and self.has_age_and_gender
        )

    @cached_property
    def improving_with_creatinines_age_gender_no_stage_or_baselinecreatinine(self) -> bool:
        return self.improving_with_creatinines and (
            not self.stage and not self.baselinecreatinine and self.has_age_and_gender
        )

    @cached_property
    def has_age_and_gender(self) -> bool:
        return self.age and self.gender is not None

    @cached_property
    def most_recent_creatinine(self) -> "Creatinine":
        return self.creatinines.first() if isinstance(self.creatinines, models.QuerySet) else self.creatinines[0]

    @cached_property
    def resolved(self) -> bool:
        return self.status == Statuses.RESOLVED

    def __str__(self) -> str:
        return f"AKI, {self.get_status_display()}"

    def update(self, status: Statuses) -> None:
        if self.status != status:
            self.status = status
            self.save()

gouthelper/blog/models.py
from autoslug import AutoSlugField  # type: ignore
from django.conf import settings  # type: ignore
from django.db import models  # type: ignore
from django.urls import reverse  # type: ignore
from django_extensions.db.models import TimeStampedModel  # type: ignore
from markdownfield.models import RenderedMarkdownField  # type: ignore
from markdownfield.validators import VALIDATOR_CLASSY  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..utils.fields import GoutHelperMarkdownField
from ..utils.helpers import now_date
from ..utils.models import GoutHelperModel
from .choices import StatusChoices


class Blogtag(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store tags for posts."""

    history = HistoricalRecords()
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Blogpost(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model to store Blog Posts as HTML Markdown pages."""

    class Meta:
        constraints = [
            # Constrain title to be unique for entire table
            models.UniqueConstraint(
                fields=["title"],
                name="%(app_label)s_%(class)s_unique_title",
            ),
            # Enforce that status is a valid StatusChoices choice
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_valid_status",
                check=models.Q(status__in=StatusChoices.values),
            ),
        ]

    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blogposts")
    history = HistoricalRecords()
    published_date = models.DateField(default=now_date)
    slug = AutoSlugField(populate_from="title", unique=True)
    status = models.CharField(max_length=20, choices=StatusChoices.choices, default="draft")
    tags = models.ManyToManyField(to=Blogtag, related_name="posts", blank=True)
    text = GoutHelperMarkdownField(rendered_field="text_rendered", validator=VALIDATOR_CLASSY)
    text_rendered = RenderedMarkdownField()
    title = models.CharField(max_length=255)
    updated_date = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

gouthelper/dateofbirths/models.py
from datetime import timedelta
from typing import TYPE_CHECKING

from django.conf import settings
from django.db import models  # type: ignore
from django.urls import reverse_lazy
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _
from django_extensions.db.models import TimeStampedModel  # type: ignore
from rules.contrib.models import RulesModelBase, RulesModelMixin  # type: ignore
from simple_history.models import HistoricalRecords  # type: ignore

from ..utils.models import GoutHelperModel  # type: ignore

if TYPE_CHECKING:
    from datetime import date


# Create your models here.
class DateOfBirth(RulesModelMixin, GoutHelperModel, TimeStampedModel, metaclass=RulesModelBase):
    """Model definition for DateOfBirth.
    Optional user OneToOneField for easy access to user's date of birth."""

    class Meta:
        # Create constraint such that date of birth is not any year before
        # exactly 18 years ago from now
        constraints = [
            models.CheckConstraint(
                check=models.Q(value__lte=(models.functions.Now() - timedelta(days=365 * 18))),
                name="dateofbirth_18_years_or_older",
            )
        ]

    value = models.DateField(
        _("Age"),
        help_text=format_lazy(
            """How old is the patient (range: 18-120)? <a href="{}" target="_next">Why do we need to know?</a>""",
            reverse_lazy("dateofbirths:about"),
        ),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        """Unicode representation of DateOfBirth."""
        return f"{self.value}"

    def value_needs_update(
        self,
        value: "date",
    ) -> bool:
        return self.value != value

    def update_value(
        self,
        value: "date",
        commit: bool = True,
    ) -> None:
        self.value = value
        if commit:
            self.full_clean()
            self.save()

gouthelper/templates/flareaids/card.html
<div id="flareaid-card" class="card text-center spacious-cards">
  <div class="card-body">
    <h2 class="card-title">FlareAid</h2>
    <p class="card-text">
      Treatment of gout flares isn't rocket science, but there are some considerations when determining
      the best treatment for a patient and his or her flare. GoutHelper's <strong>FlareAid</strong> tool
      helps you determine what the best treatment is for your patient.
    </p>
    <a href="{% url 'flareaids:create' %}"
       class="btn btn-primary spacious-buttons">Create</a>
    <a href="{% url 'flareaids:about' %}"
       class="btn btn-primary spacious-buttons">About</a>
  </div>
</div>

gouthelper/templates/flareaids/flareaid_detail_card.html
{% load project_tags %}

<div id="flareaid-card" class="card spacious-cards">
  <div class="card-body" id="flareaid">
    {% if flareaid %}
      <div class="row">
        <div class="col">
          <h4 class="card-title">
            {% if flareaid.user %}
              {% if flare %}
                <!-- djlint:off --><a href="{% url 'flareaids:pseudopatient-flare-detail' flareaid.user.pk flare.pk %}"><!-- djlint:on -->
              {% else %}
                <!-- djlint:off --><a href="{% url 'flareaids:pseudopatient-detail' flareaid.user.pk %}"><!-- djlint:on -->
              {% endif %}
            {% else %}
              <a href="{% url 'flareaids:detail' flareaid.pk %}">
              {% endif %}
              FlareAid:
              {% if flareaid.recommendation %}
                {{ flareaid.recommendation.0.lower.capitalize }}
              {% else %}
                Rheumatologist Required
              {% endif %}
            </a>
          </h4>
        </div>
        <div class="col-auto align-items-center d-flex justify-content-end">
          <button class="btn btn-secondary"
                  id="flareaid-card_collapse_control"
                  data-bs-toggle="collapse"
                  data-bs-target="#flareaid-card_collapse"
                  type="button"
                  aria-expanded="true"
                  aria-controls="flareaid-card_collapse">
            {% if show %}
              Hide
            {% else %}
              Show
            {% endif %}
          </button>
        </div>
      </div>
      <!-- djlint:off --><div class="collapse {% if show %}show {% endif %}mini-card-content"
      id="flareaid-card_collapse"><!-- djlint:on -->
      <div class="row">
        <div class="col">
          {% if flareaid.recommendation %}
            {% call_method flareaid 'treatment_dosing_dict' flareaid.recommendation.0 False as dosing_dict %}
            <ul>
              {% for key, val in dosing_dict.items %}
                <li>
                  <strong>{{ key }}</strong>: {{ val }}
                </li>
              {% endfor %}
            </ul>
          {% else %}
            <ul>
              <li>{{ flareaid.recommendation_is_none_str }}</li>
            </ul>
          {% endif %}
        </div>
      </div>
      {% if flareaid.user %}
        {% if flare %}
          <a href="{% url 'flareaids:pseudopatient-flare-update' flareaid.user.pk flare.pk %}?next={{ request.path }}"
             class="btn btn-primary">Update</a>
        {% else %}
          <a href="{% url 'flareaids:pseudopatient-update' flareaid.user.pk %}?next={{ request.path }}"
             class="btn btn-primary">Update</a>
        {% endif %}
      {% else %}
        <a href="{% url 'flareaids:update' flareaid.pk %}?next={{ request.path }}"
           class="btn btn-primary">Update</a>
      {% endif %}
      <a href="{% url 'flareaids:about' %}" class="btn btn-primary">About</a>
    </div>
  {% else %}
    <div class="row">
      <div class="col">
        <h4 class="card-title">
          <a href="{% url 'flareaids:about' %}">FlareAid</a>:
          {% if card_title %}
            {{ card_title }}
          {% else %}
            none
          {% endif %}
        </h4>
        {% if flare %}
          {% if flare.likelihood_equivocal %}
            <span><strong>WARNING:</strong> It's not certain these symptoms are due to gout. Gout treatment may not be appropriate
            or effective for other conditions and could potentially be harmful.</span>
          {% elif flare.likelihood_unlikely %}
            <span><strong>WARNING:</strong> These symptoms are probably not due to gout. Treatments directed at the correct
            diagnosis would be ideal.</span>
          {% endif %}
        {% endif %}
      </div>
      <div class="col-auto">
        {% if object|is_pseudopatient %}
          <a type="button"
             class="btn btn-primary"
             href="{% url 'flareaids:pseudopatient-create' pseudopatient=object.pk %}?next={{ request.path }}"
             role="button">Create</a>
        {% elif object.user %}
          {% if flare %}
            <a type="button"
               class="btn btn-primary"
               href="{% url 'flareaids:pseudopatient-flare-create' pseudopatient=object.user.pk flare=flare.pk %}?next={{ request.path }}"
               role="button">Create</a>
          {% else %}
            <a type="button"
               class="btn btn-primary"
               href="{% url 'flareaids:pseudopatient-create' pseudopatient=object.user.pk %}?next={{ request.path }}"
               role="button">Create</a>
          {% endif %}
        {% elif flare %}
          <a type="button"
             class="btn btn-primary"
             href="{% url 'flareaids:flare-create' flare=object.pk %}?next={{ request.path }}"
             role="button">Create</a>
        {% else %}
          <a type="button"
             class="btn btn-primary"
             href="{% url 'flareaids:create' %}?next={{ request.path }}"
             role="button">Create</a>
        {% endif %}
      </div>
    </div>
  {% endif %}
</div>
</div>

gouthelper/templates/flareaids/flareaid_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load project_tags %}

{% block title %}
  {% if form.instance.created %}
    Edit FlareAid
  {% else %}
    New FlareAid
  {% endif %}
{% endblock title %}
{% block heading %}
  {% if form.instance.created %}
    <h1>Edit FlareAid</h1>
  {% else %}
    <h1>New FlareAid</h1>
  {% endif %}
{% endblock heading %}
{% block subheading %}
  {% if form.instance.created %}
    Edit
    {% if patient %}
      {{ patient }}'s
    {% else %}
      this
    {% endif %}
    FlareAid for updated recommendations.
  {% else %}
    Create treatment recommendations for
    {% if view.related_object %}
      the patient's ({{ view.related_object.age }}{{ view.related_object.gender_abbrev }}) gout flare ({{ view.related_object.dates }}).
    {% else %}
      {{ str_attrs.subject_the_pos }} gout flares.
    {% endif %}
  {% endif %}
{% endblock subheading %}
{% block content %}
  <main class="container">
    {% if form.instance.created %}
      {% if view.kwargs.pseudopatient %}
        {% if flare %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'flareaids:pseudopatient-flare-update' object.user.pk flare.pk %}">
            {% csrf_token %}
            {% crispy form %}
            {% include '_next_inputs.html' %}
            {% include '_submit_button.html' %}
          </form>
        {% else %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'flareaids:pseudopatient-update' object.user.pk %}">
            {% csrf_token %}
            {% crispy form %}
            {% include '_next_inputs.html' %}
            {% include '_submit_button.html' %}
          </form>
        {% endif %}
      {% else %}
        <form class="form-horizontal"
              method="post"
              action="{% url 'flareaids:update' object.pk %}">
          {% csrf_token %}
          {% crispy form %}
          {% include '_next_inputs.html' %}
          {% include '_submit_button.html' %}
        </form>
      {% endif %}
    {% else %}
      {% if view.kwargs.pseudopatient %}
        {% if flare %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'flareaids:pseudopatient-flare-create' view.kwargs.pseudopatient flare.pk %}">
            {% csrf_token %}
            {% crispy form %}
            {% include '_next_inputs.html' %}
            {% include '_submit_button.html' %}
          </form>
        {% else %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'flareaids:pseudopatient-create' view.kwargs.pseudopatient %}">
            {% csrf_token %}
            {% crispy form %}
            {% include '_next_inputs.html' %}
            {% include '_submit_button.html' %}
          </form>
        {% endif %}
      {% else %}
        {% if view.related_object %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'flareaids:flare-create' view.related_object.pk %}">
            {% csrf_token %}
            {% crispy form %}
            {% include '_next_inputs.html' %}
            {% include '_submit_button.html' %}
          </form>
        {% else %}
          <form class="form-horizontal"
                method="post"
                action="{% url 'flareaids:create' %}">
            {% csrf_token %}
            {% crispy form %}
            {% include '_next_inputs.html' %}
            {% include '_submit_button.html' %}
          </form>
        {% endif %}
      {% endif %}
    {% endif %}
  </main>
{% endblock content %}
{% block inline_javascript %}
  {{ block.super }}
  {% with dob_optional=False gender_optional=True %}
    {% include 'medhistorydetails/_ckddetail_js.html' %}
  {% endwith %}
{% endblock inline_javascript %}